import express from "express";
import { protect, requireIndustry } from "../middleware/auth.middleware.js";
import { getIndustryProfile, updateIndustryProfile, getIndustryCapabilities, saveIndustryCapabilities } from "../controllers/industryController.js";
import { getIndustryInvitations, acceptIndustryInvitation, declineIndustryInvitation } from "../controllers/industryInvitationController.js";
import { getIndustryContributions, createIndustryContribution, updateIndustryContribution } from "../controllers/industryContributionController.js";
import { getIndustryOpportunities } from "../controllers/opportunityController.js";
const router = express.Router();
router.use(protect, requireIndustry);
router.get("/profile", getIndustryProfile);
router.patch("/profile", updateIndustryProfile);
router.get("/capabilities", getIndustryCapabilities);
router.put("/capabilities", saveIndustryCapabilities);
router.get("/invitations", getIndustryInvitations);
router.patch("/invitations/:invitationId/accept", acceptIndustryInvitation);
router.patch("/invitations/:invitationId/decline", declineIndustryInvitation);
router.get("/contributions", getIndustryContributions);
router.post("/contributions", createIndustryContribution);
router.patch("/contributions/:contributionId", updateIndustryContribution);
router.get("/opportunities", getIndustryOpportunities);
export default router;
