CREATE TABLE "UniversityProject" ("id" TEXT NOT NULL, "reportId" TEXT NOT NULL, "universityId" TEXT NOT NULL, "invitationId" TEXT NOT NULL, "status" TEXT NOT NULL DEFAULT 'TEAM_FORMATION', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "UniversityProject_pkey" PRIMARY KEY ("id"));
CREATE TABLE "StudentTeam" ("id" TEXT NOT NULL, "projectId" TEXT NOT NULL, "universityId" TEXT NOT NULL, "name" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "StudentTeam_pkey" PRIMARY KEY ("id"));
CREATE TABLE "StudentTeamMember" ("id" TEXT NOT NULL, "teamId" TEXT NOT NULL, "studentId" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "StudentTeamMember_pkey" PRIMARY KEY ("id"));
CREATE TABLE "UniversitySolution" ("id" TEXT NOT NULL, "projectId" TEXT NOT NULL, "reportId" TEXT NOT NULL, "universityId" TEXT NOT NULL, "teamId" TEXT NOT NULL, "title" TEXT NOT NULL, "description" TEXT NOT NULL, "technologies" JSONB, "estimatedCost" TEXT, "estimatedDuration" TEXT, "implementationPlan" TEXT, "status" TEXT NOT NULL DEFAULT 'DRAFT', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "UniversitySolution_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "UniversityProject_invitationId_key" ON "UniversityProject"("invitationId");
CREATE INDEX "UniversityProject_universityId_status_idx" ON "UniversityProject"("universityId", "status");
CREATE INDEX "UniversityProject_reportId_idx" ON "UniversityProject"("reportId");
CREATE UNIQUE INDEX "StudentTeam_projectId_key" ON "StudentTeam"("projectId");
CREATE INDEX "StudentTeam_universityId_idx" ON "StudentTeam"("universityId");
CREATE UNIQUE INDEX "StudentTeamMember_teamId_studentId_key" ON "StudentTeamMember"("teamId", "studentId");
CREATE INDEX "StudentTeamMember_studentId_idx" ON "StudentTeamMember"("studentId");
CREATE UNIQUE INDEX "UniversitySolution_teamId_key" ON "UniversitySolution"("teamId");
CREATE INDEX "UniversitySolution_projectId_status_idx" ON "UniversitySolution"("projectId", "status");
CREATE INDEX "UniversitySolution_reportId_idx" ON "UniversitySolution"("reportId");
CREATE INDEX "UniversitySolution_universityId_idx" ON "UniversitySolution"("universityId");
ALTER TABLE "UniversityProject" ADD CONSTRAINT "UniversityProject_reportId_fkey" FOREIGN KEY ("reportId") REFERENCES "Report"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "UniversityProject" ADD CONSTRAINT "UniversityProject_universityId_fkey" FOREIGN KEY ("universityId") REFERENCES "University"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "UniversityProject" ADD CONSTRAINT "UniversityProject_invitationId_fkey" FOREIGN KEY ("invitationId") REFERENCES "UniversityProblemInvitation"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "StudentTeam" ADD CONSTRAINT "StudentTeam_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "UniversityProject"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "StudentTeam" ADD CONSTRAINT "StudentTeam_universityId_fkey" FOREIGN KEY ("universityId") REFERENCES "University"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "StudentTeamMember" ADD CONSTRAINT "StudentTeamMember_teamId_fkey" FOREIGN KEY ("teamId") REFERENCES "StudentTeam"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "StudentTeamMember" ADD CONSTRAINT "StudentTeamMember_studentId_fkey" FOREIGN KEY ("studentId") REFERENCES "Student"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "UniversitySolution" ADD CONSTRAINT "UniversitySolution_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "UniversityProject"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "UniversitySolution" ADD CONSTRAINT "UniversitySolution_reportId_fkey" FOREIGN KEY ("reportId") REFERENCES "Report"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "UniversitySolution" ADD CONSTRAINT "UniversitySolution_universityId_fkey" FOREIGN KEY ("universityId") REFERENCES "University"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "UniversitySolution" ADD CONSTRAINT "UniversitySolution_teamId_fkey" FOREIGN KEY ("teamId") REFERENCES "StudentTeam"("id") ON DELETE CASCADE ON UPDATE CASCADE;
